version: "3"
services:
    web:
        build: .
        stdin_open: true
        tty: true
        ports:
            - "5000:5000"
        volumes:
            - "/app/node_modules"
            - ".:/app"