version: "2.4"
services:
  db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - db_network
  web:
    build: ./frontend
    stdin_open: true
    tty: true
    ports:
        - "5000:5000"
    environment:
      - HOST_HOST_BALANCER=http://52.15.117.25:5001    
    volumes:
        - "/app/node_modules"
        - "./frontend:/app"    
  server1:
    build: ./server1
    container_name: eli
    restart: always
    ports:
      - "3001"
    networks:
      - service_network
      - db_network 
    environment:
      - HOST_DB=db
      - CARNET=201709426
  server2:
    build: ./server1
    container_name: alison
    restart: always
    ports:
      - "3001"
    networks:
      - service_network
      - db_network
    environment:
      - HOST_DB=db
      - CARNET=201700378
  server3:
    build: ./server1
    container_name: juan
    restart: always
    ports:
      - "3001"
    networks:
      - service_network
      - db_network
    environment:
      - HOST_DB=db
      - CARNET=201700556      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3
    ports:
      - "5001:5001"
    networks:
      - service_network
       
networks:
  service_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.35.71.0/24
          gateway: 172.35.71.1
  db_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/24
          gateway: 10.10.11.1
  frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.51.0/24
          gateway: 192.168.51.1          