version: '2.0'
services:
  db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - db_network
  serverp1:
    container_name: server1
    build: ./server1
    restart: always
    ports:
      - "3001"
    networks:
      - db_network
      - service_network
    enviorments:
      - HOST_DB=db
      - CARNET=201709426
  serverp2:
    container_name: server2
    build: ./server1
    restart: always
    ports:
      - "3001"
    networks:
      - db_network
      - service_network
    enviorments:
      - HOST_DB=db
      - CARNET=201700324
  balanceador:
    container_name: balanceadorp2
    image: nginx
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
    ports:
      - "5000:5000"
    networks:
      - service_network      
    
networks:
  service_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.35.71.0/24
          gateway: 172.35.71.1
  db_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/24
          gateway: 10.10.11.1       